export { default as AnswerCard } from './AnswerCard/AnswerCard'
export { default as Question } from './Question/Question'
export { default as QuizChart } from './QuizChart/QuizChart'
export { default as QuizIntroduction } from './QuizIntroduction/QuizIntroduction'
export { default as WrongAnswer } from './WrongAnswer/WrongAnswer'
